### PR TITLE
Explicitly test against Active Record 4.2 - 5.2 and supported rubies

### PR DESCRIPTION
**Pull request by brendon**
Ruby 2.3 is EOL but I kept it in anyway. It's likely I'll have configured something wrong but we'll see if this runs anyway. All tests pass up to 5.2 locally. We could look at extending this to test MySQL and Postgresql but you might be able to comment on whether any of the code actually would invoke differences between the database engines?

### CODE REVIEW

**Comment by brendon** [comment]
For some reason Travis isn't building against my PR but I've activated it for my repo here:

https://travis-ci.org/brendon/traco/builds/544990823

**Comment by brendon** [comment]
Ok, we're good to go: https://travis-ci.org/brendon/traco/builds/545025538

Still not sure why Travis didn't run for this PR. You might have to configure it to run for PR's on your end? I did muck up slightly by doing my changes on my own master branch instead of a new branch but that's probably neither here nor there :)

**Comment by brendon** [comment]
Also, upon reviewing the code, you're definitely not doing anything in the tests that interacts with the database bar actually just creating the table so this is good to go :)

**Comment by henrik** [comment]
Thank you so much, @brendon :) This is lovely. Yeah, like you say, shouldn't be anything DB engine specific.

**Comment by henrik** [comment]
The project wasn't "active" in Travis, whatever that means. Hopefully fixed now!

**Comment by henrik** [comment]
CI is happy! https://travis-ci.org/barsoom/traco 🎉

**Comment by brendon** [comment]
Thanks @henrik :D My pleasure. Glad Travis is behaving himself now :)

**Pull request merged**
